language: go

env:
- GO111MODULE=on

go:
  - "1.8"
  - "1.11.x"
  - "1.x" # latest

script:
  - go test -v ./...

# before we deploy, we go build for all operating systems we would like to support
before_deploy:
  - mkdir -p release
  - "GOOS=linux  GOARCH=amd64 go build -o release/terraform-inventory_linux_amd64"
  - "GOOS=darwin GOARCH=amd64 go build -o release/terraform-inventory_darwin_amd64"
# Windows doesn't work yet, due to the readonly segment
#  - "GOOS=windows GOARCH=amd64 go build -o release/powerline-go-windows-amd64"

deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_API_KEY"
  file:
    - "release/terraform-inventory_linux_amd64"
    - "release/terraform-inventory_darwin_amd64"
# Windows doesn't work yet, due to the readonly segment
#    - "release/powerline-go-windows-amd64"
  skip_cleanup: true
  on:
    tags: true
